(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("c74e83f8aa4c78a121b52146eadb792c9facc5b1f02c917e3dbb454fca931223" "a27c00821ccfd5a78b01e4f35dc056706dd9ede09a8b90c6955ae6a390eb1c1e" "3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" default))
 '(package-selected-packages
   '(ace-window
     annotate
     async
     auctex
     avy
     bash-completion
     cmake-font-lock
     cmake-mode
     consult
     cyphejor
     dash
     deferred
     docker
     docker-tramp
     dockerfile-mode
     edit-server
     eglot
     ein
     eldoc
     elfeed
     embark
     embark-consult
     emms
     expand-region
     exwm
     f
     fd-dired
     figlet
     flymake
     flyspell-correct
     git-commit
     gnuplot
     gnuplot-mode
     go-mode
     goto-chg
     graphviz-dot-mode
     grugru
     guess-language
     haskell-mode
     hide-comnt
     hl-todo
     ht
     htmlize
     hydra
     imenu-anywhere
     json-mode
     json-reformat
     json-snatcher
     jsonrpc
     link-hint
     lsp-mode
     lua-mode
     lv
     magit
     magit-todos
     map
     markdown-mode
     markdown-mode+
     memoize
     mini-frame
     minimap
     multiple-cursors
     ob-async
     ob-php
     ob-rust
     orderless
     org
     org-agenda-property
     org-brain
     org-noter
     org-super-agenda
     org-tree-slide
     ov
     ox-gfm
     ox-mediawiki
     ox-rst
     ox-textile
     ox-twbs
     pcre2el
     php-mode
     plantuml-mode
     polymode
     project
     protobuf-mode
     queue
     rainbow-delimiters
     rebox2
     request
     request-deferred
     rg
     rust-mode
     s
     spinner
     stickyfunc-enhance
     string-inflection
     swap-regions
     syslog-mode
     tablist
     thingatpt+
     transient
     transpose-frame
     tree-sitter
     tree-sitter-langs
     ts
     typescript-mode
     undo-propose
     undo-tree
     vdiff
     vertico
     vimish-fold
     virtualenvwrapper
     vlf
     vterm
     web-mode
     websocket
     wgrep
     which-key
     with-editor
     xahk-mode
     xclip
     xelb
     xref
     xterm-color
     yaml-mode
     yasnippet
     yasnippet-snippets))
 '(safe-local-variable-values
   '((org-babel-min-lines-for-block-output . 99)
     (org-confirm-babel-evaluate)
     (org-babel-noweb-wrap-end . "»")
     (org-babel-noweb-wrap-start . "«"))))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
