(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("c74e83f8aa4c78a121b52146eadb792c9facc5b1f02c917e3dbb454fca931223" "a27c00821ccfd5a78b01e4f35dc056706dd9ede09a8b90c6955ae6a390eb1c1e" "3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" default))
 '(helm-ff-keep-cached-candidates nil)
 '(package-selected-packages
   '(ace-window
     anaphora
     annotate
     async
     auctex
     avy
     bash-completion
     bookmark+
     cmake-font-lock
     cmake-mode
     cyphejor
     dash
     dash-functional
     deferred
     docker
     docker-tramp
     dockerfile-mode
     edit-server
     eglot
     ein
     eldoc
     elfeed
     emms
     epl
     exec-path-from-shell
     expand-region
     exwm
     f
     fd-dired
     figlet
     flymake
     flyspell-correct
     git-commit
     gnuplot
     gnuplot-mode
     go-mode
     graphviz-dot-mode
     guess-language
     haskell-mode
     hide-comnt
     hl-todo
     ht
     htmlize
     hydra
     icomplete-vertical
     imenu-anywhere
     json-mode
     json-reformat
     json-snatcher
     let-alist
     link-hint
     lua-mode
     lv
     magit
     magit-todos
     map
     markdown-mode
     markdown-mode+
     memoize
     mini-frame
     minimap
     multiple-cursors
     noccur
     ob-async
     objed
     orderless
     org
     org-agenda-property
     org-brain
     org-noter
     org-plus-contrib
     org-ql
     org-super-agenda
     ov
     ox-gfm
     ox-mediawiki
     ox-rst
     ox-twbs
     pcre2el
     peg
     php-mode
     pkg-info
     plantuml-mode
     polymode
     project
     projectile
     protobuf-mode
     rainbow-delimiters
     rebox2
     request
     request-deferred
     rg
     rust-mode
     s
     stickyfunc-enhance
     string-inflection
     swap-regions
     tablist
     thingatpt+
     transient
     transpose-frame
     ts
     undo-propose
     vdiff
     vimish-fold
     virtualenvwrapper
     vlf
     web-mode
     websocket
     wgrep
     which-key
     with-editor
     xahk-mode
     xelb
     xref
     xterm-color
     yaml-mode
     yasnippet
     yasnippet-snippets)))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
