;;; modal-config.el --- Configure modal

;;; Commentary:

;; Usage:
;; (require 'modal-config)

;;; Code:
(require 'modal)
(require 'indent)

(setq modal-insert-cursor-type '(bar . 4)
      modal-cursor-type '(hbar . 7)
      modal-excluded-modes '(eshell-mode
                             calc-mode
                             magit-popup-mode
                             magit-mode
                             magit-process-mode
                             magit-status-mode
                             docker-container-mode))

;;;;;;;;;;
;; Keys ;;
;;;;;;;;;;

(define-key indent-rigidly-map "F" #'indent-rigidly-right-to-tab-stop)
(define-key indent-rigidly-map "B" #'indent-rigidly-left-to-tab-stop)
(define-key indent-rigidly-map "f" #'indent-rigidly-right)
(define-key indent-rigidly-map "b" #'indent-rigidly-left)

;; Modal editing

;; ' (handy as self-inserting symbol)
;; " (handy as self-inserting symbol)
(modal-define-kbd ")" "<S-right>" "sp-forward-sexp")
(modal-define-kbd "(" "<S-left>" "sp-backward-sexp")
(modal-define-kbd "[" "C-(" "sp-rewrap-sexp-lc")
(modal-define-kbd "]" "C-)" "sp-unwrap-sexp-lc")
(define-key modal-mode-map (kbd "º") #'er/expand-region)
(define-key modal-mode-map (kbd "ª") #'er/contract-region)
(modal-define-kbd "?" "C-," "goto-last-change-reverse")
(modal-define-kbd "." "M-." "definition-at-point")
(modal-define-kbd "/" "C-." "goto-last-change")
(modal-define-kbd ";" "M-;" "comment-dwim")
(modal-define-kbd ":" "M-:" "eval-expression")
(modal-define-kbd "-" "C-_" "undo-tree-undo")
(modal-define-kbd "_" "M-_" "undo-tree-redo")
(modal-define-kbd "," "M-," "declaration-at-point")
(modal-define-kbd "%" "M-%" "query-replace")
(modal-define-kbd "*" "C-*" "duplicate-current-line-or-region")
(modal-define-kbd "<" "M-<" "beginning-of-buffer")
(modal-define-kbd ">" "M->" "end-of-buffer")
(modal-define-kbd "SPC" "C-SPC" "set-mark-command")

(modal-define-kbd "0" "C-0" "prefix-0")
(modal-define-kbd "1" "C-1" "prefix-1")
(modal-define-kbd "2" "C-2" "prefix-2")
(modal-define-kbd "3" "C-3" "prefix-3")
(modal-define-kbd "4" "C-4" "prefix-4")
(modal-define-kbd "5" "C-5" "prefix-5")
(modal-define-kbd "6" "C-6" "prefix-6")
(modal-define-kbd "7" "C-7" "prefix-7")
(modal-define-kbd "8" "C-8" "prefix-8")
(modal-define-kbd "9" "C-9" "prefix-9")

(modal-define-kbd "a" "C-a" "move-beginning-of-line")
(modal-define-kbd "b" "C-b" "backward-char")
(define-key modal-mode-map (kbd "c ! c") #'flycheck-buffer)
(define-key modal-mode-map (kbd "c ! n") #'flycheck-next-error)
(define-key modal-mode-map (kbd "c ! p") #'flycheck-previous-error)
(define-key modal-mode-map (kbd "c ! l") #'flycheck-list-errors)
(modal-define-kbd "c b" "C-c C-b" "go-back")
(modal-define-kbd "c c" "C-c C-c")
(define-key modal-mode-map (kbd "c e w") #'er/mark-word)
(define-key modal-mode-map (kbd "c e s") #'er/mark-symbol)
(define-key modal-mode-map (kbd "c e c") #'er/mark-method-call)
(define-key modal-mode-map (kbd "c e q") #'er/mark-inside-quotes)
(define-key modal-mode-map (kbd "c e Q") #'er/mark-outside-quotes)
(define-key modal-mode-map (kbd "c e p") #'er/mark-inside-pairs)
(define-key modal-mode-map (kbd "c e P") #'er/mark-outside-pairs)
(define-key modal-mode-map (kbd "c i s") #'spanish-dictionary)
(define-key modal-mode-map (kbd "c i e") #'english-dictionary)
(define-key modal-mode-map (kbd "c i c") #'flyspell-buffer)
(define-key modal-mode-map (kbd "c i n") #'flyspell-goto-next-error)
(define-key modal-mode-map (kbd "c i p") #'flyspell-goto-previous-error)
(define-key modal-mode-map (kbd "c i a") #'flyspell-auto-correct-word)
(modal-define-kbd "c k" "C-c C-k")
(define-key modal-mode-map (kbd "c m p") #'mc/mark-previous-like-this)
(define-key modal-mode-map (kbd "c m n") #'mc/mark-next-like-this)
(define-key modal-mode-map (kbd "c m a") #'mc/mark-all-like-this-dwim)
(modal-define-kbd "c n" "C-c C-n" "smartscan-symbol-go-forward")
(modal-define-kbd "c p" "C-c C-p" "smartscan-symbol-go-backward")
(modal-define-kbd "c r" "C-c M-s" "org-sort-entries-user-defined")
(modal-define-kbd "c s" "C-c C-s" "org-schedule")
(modal-define-kbd "c t" "C-c C-t" "org-todo")
(modal-define-kbd "c u" "C-c C-u" "outline-up-heading")
(modal-define-kbd "c v" "C-c C-v")
(modal-define-kbd "d" "<deletechar>" "delete-forward-char")
(modal-define-kbd "e" "C-e" "move-end-of-line")
(modal-define-kbd "f" "C-f" "forward-char")
(modal-define-kbd "g" "C-g" "keyboard-quit")
(modal-define-kbd "h" "M-h" "mark-paragraph")
;; i - reserved
(modal-define-kbd "j" "M-j" "indent-new-comment-line")
(modal-define-kbd "k" "C-k" "kill-line")
(modal-define-kbd "l" "C-l" "recenter-top-bottom")
(modal-define-kbd "m" "C-m" "newline")
(modal-define-kbd "n" "C-n" "next-line")
(modal-define-kbd "o" "C-o" "open-line")
(modal-define-kbd "p" "C-p" "previous-line")
(modal-define-kbd "r" "C-r" "isearch-backward")
(modal-define-kbd "s" "C-s" "isearch-forward")
(modal-define-kbd "t" "C-t" "transpose-chars")
;; u - reserved
(modal-define-kbd "v" "C-v" "scroll-up-command")
(modal-define-kbd "w" "C-w" "kill-region")
(modal-define-kbd "x TAB" "C-x TAB" "indent-rigidly")
(modal-define-kbd "x RET" "C-x C-o" "delete-blank-lines")
(modal-define-kbd "x SPC" "M-SPC" "fixup-whitespace")
(modal-define-kbd "x ;" "C-x C-;" "comment-line")
(modal-define-kbd "x 0" "C-x 0" "delete-window")
(modal-define-kbd "x 1" "C-x 1" "delete-other-windows")
(modal-define-kbd "x 2" "C-x 2" "vsplit-last-buffer")
(modal-define-kbd "x 3" "C-x 3" "hsplit-last-buffer")
(modal-define-kbd "x 5" "C-x +" "balance-windows")
(modal-define-kbd "x 6" "C-c <left>" "windmove-left")
(modal-define-kbd "x 7" "C-c <down>" "windmove-down")
(modal-define-kbd "x 8" "C-c <up>" "windmove-up")
(modal-define-kbd "x 9" "C-c <right>" "windmove-right")
(modal-define-kbd "x (" "C-x (" "kmacro-start-macro")
(modal-define-kbd "x )" "C-x )" "kmacro-end-macro")
(modal-define-kbd "x c" "C-x C-c" "save-buffers-kill-emacs")
(modal-define-kbd "x b" "C-x b" "switch-buffer")
(modal-define-kbd "x e" "C-x C-e" "eval-last-sexp")
(modal-define-kbd "x f" "C-x C-f" "find-file")
(modal-define-kbd "x F" "C-x f" "find-file-at-point")
(modal-define-kbd "x K" "C-x k" "kill-buffer")
(modal-define-kbd "x s" "C-x C-s" "save-buffer")
(modal-define-kbd "x S" "C-x s" "save-some-buffers")
(modal-define-kbd "x r" "C-x C-r" "recentf-open")
(modal-define-kbd "y" "C-y" "yank")
(modal-define-kbd "z" "M-z" "avy-goto-char-timer")

(modal-define-kbd "A" "M-a")
(modal-define-kbd "B" "M-b")
(modal-define-kbd "C" "M-c")
(modal-define-kbd "D" "M-d")
(modal-define-kbd "E" "M-e")
(modal-define-kbd "F" "M-f")
(modal-define-kbd "G g" "M-g g" "goto-line")
(modal-define-kbd "G G" "M-g M-g" "goto-line")
(modal-define-kbd "H" "M-H")
(modal-define-kbd "I" "M-i")
(define-key modal-mode-map (kbd "S-j") #'avy-goto-line)
(modal-define-kbd "K" "M-k")
(modal-define-kbd "L" "M-l")
(modal-define-kbd "M" "M-m")
(modal-define-kbd "N" "M-n")
(modal-define-kbd "O" "M-o")
(modal-define-kbd "Q" "M-q")
(modal-define-kbd "P" "M-p")
(modal-define-kbd "R" "M-r")
(modal-define-kbd "S" "M-S")
(modal-define-kbd "T" "M-t")
(modal-define-kbd "U" "M-u")
(modal-define-kbd "V" "M-v")
(modal-define-kbd "W" "M-w")
(modal-define-kbd "X" "M-x")
(modal-define-kbd "Y" "M-y")
(modal-define-kbd "Z" "C-x z")


(modal-global-mode 1)


(provide 'modal-config)
;;; modal-config.el ends here
