;;; prettify-symbols-config.el --- Configure prettify-symbols

;;; Commentary:

;; Usage:
;; (require 'prettify-symbols-config)

;;; Code:

;;(global-prettify-symbols-mode)

(require 'config-lib)

(defun prettify-symbols-emacs-lisp-mode-hook ()
  (if (display-graphic-p)
      (progn
        (cl-delete '("lambda" . 995) prettify-symbols-alist)
        (push '("lambda" . (?\s (Br . Bl) ?\s (Br . Bl) ?λ (Br . Bl) ?· (Br . Bl) ?\s (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '("nil" . (?\s (Br . Bl) ?∅ (Br . Bl) ?\s)) prettify-symbols-alist))
    (push '("nil" . ?∅) prettify-symbols-alist)))

(defun prettify-symbols-c-mode-common-hook ()
  (push '("!"     . ?¬) prettify-symbols-alist)
  (push '("="     . ?≔) prettify-symbols-alist)
  (if (display-graphic-p)
      (progn
        (push '("true"  . (?\s (Br . Bl) ?\s (Br . Bl) ?\s (Br . Bl) ?\s (Bc . Bc) ?✓)) prettify-symbols-alist)
        (push '("false" . (?\s (Br . Bl) ?\s (Br . Bl) ?\s (Br . Bl) ?\s (Br . Bl) ?\s (Bc . Bc) ?✘)) prettify-symbols-alist)
        (push '("&&"    . (?\s (Br . Bl) ?\s (Bc . Bc) ?∧)) prettify-symbols-alist)
        (push '("||"    . (?\s (Br . Bl) ?\s (Bc . Bc) ?∨)) prettify-symbols-alist)
        (push '("->"    . (?\s (Br . Bl) ?\s (Bc . Bc) ?→)) prettify-symbols-alist)
        (push '("::"    . (?\s (Br . Bl) ?\s (Bc . Bc) ?⊃)) prettify-symbols-alist)
        (push '("::~"   . (?\s (Br . Bl) ?\s (Br . Bl) ?\s (Bc . Br) ?⊃ (Bc . Bl) ?~)) prettify-symbols-alist)
        (push '(">::"   . (?\s (Br . Bl) ?\s (Br . Bl) ?\s (Bl . Bl) ?> (Bc . Bl) ?⊃)) prettify-symbols-alist)
        (push '("->*"   . (?\s (Br . Bl) ?\s (Br . Bl) ?\s (Bc . Br) ?→ (Br . Br) ?*)) prettify-symbols-alist))
    (push '("true"  . ?✓) prettify-symbols-alist)
    (push '("false" . ?✘) prettify-symbols-alist)
    (push '("&&"    . ?∧) prettify-symbols-alist)
    (push '("||"    . ?∨) prettify-symbols-alist)
    (push '("->"    . ?→) prettify-symbols-alist)
    (push '("::"    . ?⊃) prettify-symbols-alist)))

(defun prettify-symbols-c-mode-hook ()
  (if (display-graphic-p)
      (progn
        (push '("!="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≠)) prettify-symbols-alist)
        (push '("<="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≤)) prettify-symbols-alist)
        (push '(">="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≥)) prettify-symbols-alist)
        (push '("=="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≡)) prettify-symbols-alist))
    (push '("!="    . ?≠) prettify-symbols-alist)
    (push '("<="    . ?≤) prettify-symbols-alist)
    (push '(">="    . ?≥) prettify-symbols-alist)
    (push '("=="    . ?≡) prettify-symbols-alist)))

(defun prettify-symbols-c++-mode-hook ()
  (if (display-graphic-p)
      (progn
        (push '("!="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≠)) prettify-symbols-alist)
        (push '("<="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≤)) prettify-symbols-alist)
        (push '(">="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≥)) prettify-symbols-alist)
        (push '("=="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≡)) prettify-symbols-alist))
    (push '("!="    . ?≠) prettify-symbols-alist)
    (push '("<="    . ?≤) prettify-symbols-alist)
    (push '(">="    . ?≥) prettify-symbols-alist)
    (push '("=="    . ?≡) prettify-symbols-alist)))

(defun prettify-symbols-php-mode-hook ()
  (if (display-graphic-p)
      (progn
        (push '("!=="   . (?\s (Br . Bl) ?≠ (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '("<=="   . (?\s (Br . Bl) ?≤ (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '(">=="   . (?\s (Br . Bl) ?≥ (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '("==="   . (?\s (Br . Bl) ?≡ (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '("!="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≉)) prettify-symbols-alist)
        (push '("<="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≲)) prettify-symbols-alist)
        (push '(">="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≳)) prettify-symbols-alist)
        (push '("=="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≈)) prettify-symbols-alist))
    (push '("!=="   . ?≠) prettify-symbols-alist)
    (push '("<=="   . ?≤) prettify-symbols-alist)
    (push '(">=="   . ?≥) prettify-symbols-alist)
    (push '("==="   . ?≡) prettify-symbols-alist)
    (push '("!="    . ?≉) prettify-symbols-alist)
    (push '("<="    . ?≲) prettify-symbols-alist)
    (push '(">="    . ?≳) prettify-symbols-alist)
    (push '("=="    . ?≈) prettify-symbols-alist)))

(defun prettify-symbols-js-mode-hook ()
  (if (display-graphic-p)
      (progn
        (push '("!=="   . (?\s (Br . Bl) ?≠ (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '("<=="   . (?\s (Br . Bl) ?≤ (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '(">=="   . (?\s (Br . Bl) ?≥ (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '("==="   . (?\s (Br . Bl) ?≡ (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '("!="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≉)) prettify-symbols-alist)
        (push '("<="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≲)) prettify-symbols-alist)
        (push '(">="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≳)) prettify-symbols-alist)
        (push '("=="    . (?\s (Br . Bl) ?\s (Bc . Bc) ?≈)) prettify-symbols-alist))
    (push '("!=="   . ?≠) prettify-symbols-alist)
    (push '("<=="   . ?≤) prettify-symbols-alist)
    (push '(">=="   . ?≥) prettify-symbols-alist)
    (push '("==="   . ?≡) prettify-symbols-alist)
    (push '("!="    . ?≉) prettify-symbols-alist)
    (push '("<="    . ?≲) prettify-symbols-alist)
    (push '(">="    . ?≳) prettify-symbols-alist)
    (push '("=="    . ?≈) prettify-symbols-alist)))

(defun prettify-symbols-python-mode-hook ()
  (push '("!"     . ?¬) prettify-symbols-alist)
  (push '("="     . ?≔) prettify-symbols-alist)
  (if (display-graphic-p)
      (progn
        (cl-delete '("lambda" . 995) prettify-symbols-alist)
        (push '("lambda" . (?\s (Br . Bl) ?\s (Br . Bl) ?λ (Br . Bl) ?· (Br . Bl) ?\s (Br . Bl) ?\s)) prettify-symbols-alist)
        (push '("True"   . (?\s (Br . Bl) ?\s (Br . Bl) ?\s (Br . Bl) ?\s (Bc . Bc) ?✓)) prettify-symbols-alist)
        (push '("False"  . (?\s (Br . Bl) ?\s (Br . Bl) ?\s (Br . Bl) ?\s (Br . Bl) ?\s (Bc . Bc) ?✘)) prettify-symbols-alist)
        (push '("None"   . (?\s (Br . Bl) ?\s (Br . Bl) ?\s (Br . Bl) ?\s (Bc . Bc) ?∅)) prettify-symbols-alist)
        (push '("and"    . (?\s (Br . Bl) ?\s (Br . Bl) ?\s (Bc . Bc) ?∧)) prettify-symbols-alist)
        (push '("or"     . (?\s (Br . Bl) ?\s (Bc . Bc) ?∨)) prettify-symbols-alist)
        (push '("!="     . (?\s (Br . Bl) ?\s (Bc . Bc) ?≠)) prettify-symbols-alist)
        (push '("<="     . (?\s (Br . Bl) ?\s (Bc . Bc) ?≤)) prettify-symbols-alist)
        (push '(">="     . (?\s (Br . Bl) ?\s (Bc . Bc) ?≥)) prettify-symbols-alist)
        (push '("=="     . (?\s (Br . Bl) ?\s (Bc . Bc) ?≡)) prettify-symbols-alist))
    (push '("True"  . ?✓) prettify-symbols-alist)
    (push '("False" . ?✘) prettify-symbols-alist)
    (push '("None"  . ?∅) prettify-symbols-alist)
    (push '("and"   . ?∧) prettify-symbols-alist)
    (push '("or"    . ?∨) prettify-symbols-alist)
    (push '("!="    . ?≠) prettify-symbols-alist)
    (push '("<="    . ?≤) prettify-symbols-alist)
    (push '(">="    . ?≥) prettify-symbols-alist)
    (push '("=="    . ?≡) prettify-symbols-alist)))

(defun prettify-symbols-hooks (&optional arg)
  (interactive "P")
  (if arg
      (progn
        (remove-hook 'emacs-lisp-mode-hook 'prettify-symbols-emacs-lisp-mode-hook)
        (remove-hook 'c-mode-common-hook 'prettify-symbols-c-mode-common-hook)
        (remove-hook 'c-mode-hook 'prettify-symbols-c-mode-hook)
        (remove-hook 'c++-mode-hook 'prettify-symbols-c++-mode-hook)
        (remove-hook 'php-mode-hook 'prettify-symbols-php-mode-hook)
        (remove-hook 'js-mode-hook 'prettify-symbols-js-mode-hook)
        (remove-hook 'python-mode-hook 'prettify-symbols-python-mode-hook))
    (setq prettify-symbols-unprettify-at-point 'right-edge)
    (add-hook 'emacs-lisp-mode-hook 'prettify-symbols-emacs-lisp-mode-hook)
    (add-hook 'c-mode-common-hook 'prettify-symbols-c-mode-common-hook)
    (add-hook 'c-mode-hook 'prettify-symbols-c-mode-hook)
    (add-hook 'c++-mode-hook 'prettify-symbols-c++-mode-hook)
    (add-hook 'php-mode-hook 'prettify-symbols-php-mode-hook)
    (add-hook 'js-mode-hook 'prettify-symbols-js-mode-hook)
    (add-hook 'python-mode-hook 'prettify-symbols-python-mode-hook)))

(global-set-key (kbd "M-s 7 p") #'prettify-symbols-mode)
(global-set-key (kbd "M-s 7 P") (lambda ()
                                  (interactive)
                                  (prettify-symbols-hooks global-prettify-symbols-mode)
                                  (global-prettify-symbols-mode)))


(provide 'prettify-symbols-config)
;;; prettify-symbols-config.el ends here
